name: Feature request
description: Request a new feature for the module
labels: [feature request]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of the feature you want to be implemented.
      placeholder: A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Implementation details
      description: A description of how you'd like to see it implemented.
  - type: textarea
    id: context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
